spring:
  application:
    name: sender
server:
  port: 8082

cronPing: 10 * * * * *
cronPong: 20 * * * * *
delayPing: 10000

requestDtoDef:
  name: тест запрос
  date: 25.02.2024
  request: запрос

url:
  ping: http://localhost:8081/ping
  pong: http://localhost:8081/pong

management:
  endpoints.web.exposure.include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true